### ISSUE TITLE
package out of date

### ISSUE THREAD

**Issue by nmoore2** [max-barry/generator-jumpstart-static#1]
Hi, I'm getting this message when I run the install commands. I just updated npm and I'm on node v5.5

Here's the output:

`$ npm install generator-jumpstart-static
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN mti@1.0.0 No description
npm WARN mti@1.0.0 No repository field.
nathan.moore@:~/Sites/jumpstart$ yo generator-jumpstart-static
Error generator-jumpstart-static 

You don't seem to have a generator with the name generator-jumpstart-static installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 7 registered generators run yo with the `--help` option.`

**Comment by max-barry** [comment]
Hey there!

With all Yeoman generators, you don't actually call them with yo generator-whatever. You drop the "generator" bit.

So instead of "yo generator-jumostart-static" you will just want "to jumpstart-static"

**Comment by max-barry** [comment]
Or alternatively just "yo" and it will show all the packages you have installed. The use of "generator-" in generator package titles is to allow Yeoman to recognise it as a generator.
